# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/architecture/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from logos_sophia_sdk.models.cwma_graph_data import CWMAGraphData
from logos_sophia_sdk.models.cwme_sentiment_data import CWMESentimentData
from logos_sophia_sdk.models.cwmg_imagined_data import CWMGImaginedData
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

CWMSTATEDATA_ONE_OF_SCHEMAS = ["CWMAGraphData", "CWMESentimentData", "CWMGImaginedData"]

class CWMStateData(BaseModel):
    """
    Model-specific payload
    """
    # data type: CWMAGraphData
    oneof_schema_1_validator: Optional[CWMAGraphData] = None
    # data type: CWMGImaginedData
    oneof_schema_2_validator: Optional[CWMGImaginedData] = None
    # data type: CWMESentimentData
    oneof_schema_3_validator: Optional[CWMESentimentData] = None
    actual_instance: Optional[Union[CWMAGraphData, CWMESentimentData, CWMGImaginedData]] = None
    one_of_schemas: Set[str] = { "CWMAGraphData", "CWMESentimentData", "CWMGImaginedData" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = CWMStateData.model_construct()
        error_messages = []
        match = 0
        # validate data type: CWMAGraphData
        if not isinstance(v, CWMAGraphData):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CWMAGraphData`")
        else:
            match += 1
        # validate data type: CWMGImaginedData
        if not isinstance(v, CWMGImaginedData):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CWMGImaginedData`")
        else:
            match += 1
        # validate data type: CWMESentimentData
        if not isinstance(v, CWMESentimentData):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CWMESentimentData`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in CWMStateData with oneOf schemas: CWMAGraphData, CWMESentimentData, CWMGImaginedData. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in CWMStateData with oneOf schemas: CWMAGraphData, CWMESentimentData, CWMGImaginedData. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into CWMAGraphData
        try:
            instance.actual_instance = CWMAGraphData.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CWMGImaginedData
        try:
            instance.actual_instance = CWMGImaginedData.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CWMESentimentData
        try:
            instance.actual_instance = CWMESentimentData.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CWMStateData with oneOf schemas: CWMAGraphData, CWMESentimentData, CWMGImaginedData. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CWMStateData with oneOf schemas: CWMAGraphData, CWMESentimentData, CWMGImaginedData. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CWMAGraphData, CWMESentimentData, CWMGImaginedData]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


