# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/architecture/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from logos_sophia_sdk.models.cwm_state_data import CWMStateData
from logos_sophia_sdk.models.cwm_state_links import CWMStateLinks
from typing import Optional, Set
from typing_extensions import Self

class CWMState(BaseModel):
    """
    Unified causal world model state envelope.
    """ # noqa: E501
    state_id: StrictStr = Field(description="Globally unique identifier (`cwm_<model>_<uuid>`)")
    model_type: StrictStr
    source: StrictStr = Field(description="Subsystem that emitted the record (e.g., orchestrator, jepa_runner)")
    timestamp: datetime
    confidence: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]
    status: StrictStr
    links: CWMStateLinks
    tags: Optional[List[StrictStr]] = Field(default=None, description="Free-form labels for diagnostics filtering")
    data: CWMStateData
    __properties: ClassVar[List[str]] = ["state_id", "model_type", "source", "timestamp", "confidence", "status", "links", "tags", "data"]

    @field_validator('model_type')
    def model_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CWM_A', 'CWM_G', 'CWM_E']):
            raise ValueError("must be one of enum values ('CWM_A', 'CWM_G', 'CWM_E')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['observed', 'imagined', 'reflected', 'ephemeral']):
            raise ValueError("must be one of enum values ('observed', 'imagined', 'reflected', 'ephemeral')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CWMState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CWMState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "state_id": obj.get("state_id"),
            "model_type": obj.get("model_type"),
            "source": obj.get("source"),
            "timestamp": obj.get("timestamp"),
            "confidence": obj.get("confidence"),
            "status": obj.get("status"),
            "links": CWMStateLinks.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "tags": obj.get("tags"),
            "data": CWMStateData.from_dict(obj["data"]) if obj.get("data") is not None else None
        })
        return _obj


