# coding: utf-8

"""
    Sophia API

    Canonical Sophia OpenAPI contract for Project LOGOS. See Phase 2 specification (docs/architecture/PHASE2_SPEC.md) for behavioral details.  Sophia exposes planner and world-model endpoints backed by the Hybrid Cognitive Graph (HCG). Responses share the unified `CWMState` envelope so CLI, browser, and SDK clients consume identical data. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SimulationRequest(BaseModel):
    """
    SimulationRequest
    """ # noqa: E501
    capability_id: StrictStr = Field(description="Capability or Talos action identifier")
    context: Dict[str, Any] = Field(description="Structured context (entity IDs, sensor frames, parameters)")
    horizon_steps: Optional[Annotated[int, Field(le=50, strict=True, ge=1)]] = 5
    assumptions: Optional[List[StrictStr]] = Field(default=None, description="Optional assumptions applied to the rollout")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Miscellaneous metadata for audit trails")
    __properties: ClassVar[List[str]] = ["capability_id", "context", "horizon_steps", "assumptions", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimulationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimulationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "capability_id": obj.get("capability_id"),
            "context": obj.get("context"),
            "horizon_steps": obj.get("horizon_steps") if obj.get("horizon_steps") is not None else 5,
            "assumptions": obj.get("assumptions"),
            "metadata": obj.get("metadata")
        })
        return _obj


